/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:8da6fe5a-52f1-44be-9651-e9da9be8bbb4",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_loaGEUibk",
    "aws_user_pools_web_client_id": "7j3o8om4s9svv685pieg238a90",
    "oauth": {
        "domain": "dgapp82740aa2-82740aa2-dev.auth.us-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "exp://192.168.1.54:19001/",
        "redirectSignOut": "exp://192.168.1.54:19001/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "imagebucket231631-dev",
    "aws_user_files_s3_bucket_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://3wiys7bqx5cz3d3wll5pqnhvoi.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-zs2psskscjealhredc6zfbgmx4"
};


export default awsmobile;
